version: "3"

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

  test:
    build: .
    command: pytest tests/
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
